/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 real_portfolio.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
   const { nodes, materials } = useGLTF('/models/real_portfolio.glb');
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.Sign001_Baked.geometry}
            material={materials['Bake_Signs_Baked.003']}
            position={[1.933, 2.707, -1.238]}
         />
         <mesh
            geometry={nodes['Cup_-_Round008_Baked'].geometry}
            material={materials['Bake_Dining_Items_Baked.003']}
            position={[1.099, 1.246, -0.648]}
            rotation={[Math.PI / 2, 0, -0.934]}
         />
         <mesh
            geometry={nodes.Table_Baked.geometry}
            material={materials['Bake_Dining_Baked.002']}
            position={[1.064, 0.605, -0.448]}
         />
         <mesh
            geometry={nodes.Shelf_Baked.geometry}
            material={materials['Bake_Wall_Items_Baked.002']}
            position={[-1.129, 1.87, 0.136]}
         />
         <mesh
            geometry={nodes['Room_-_Walls_Baked'].geometry}
            material={materials['Bake_Walls_Baked.002']}
            position={[0.166, 1.432, 0.259]}
         />
         <mesh
            geometry={nodes['Hidden_table_-_1_Baked'].geometry}
            material={materials['Bake_Counter_Baked.003']}
            position={[0.638, 1.061, 1.32]}
         />
         <mesh
            geometry={nodes.croissant.geometry}
            material={materials['croissant.002']}
            position={[0.13, 1.416, 1.065]}
            rotation={[-2.742, 0.562, 2.92]}
         />
         <group position={[0.083, 1.27, 1.092]}>
            <mesh
               geometry={nodes.Torus004.geometry}
               material={materials['Donut - Base.002']}
            />
            <mesh
               geometry={nodes.Torus004_1.geometry}
               material={materials['Donut - Glaze.002']}
            />
            <mesh
               geometry={nodes.Torus004_2.geometry}
               material={materials['PaletteMaterial001.002']}
            />
         </group>
         <mesh
            geometry={nodes.Display_Base.geometry}
            material={materials['PaletteMaterial002.001']}
            position={[0.231, 1.229, 1.32]}
         />
         <mesh
            geometry={nodes.Plane.geometry}
            material={materials['PaletteMaterial003.001']}
            position={[0.219, 2.82, -1.165]}
            scale={[0.876, 0.474, 0.474]}
         />
         <mesh
            geometry={nodes.Menu_Images001.geometry}
            material={materials['Menu - Projects.002']}
            position={[-1.16, 2.493, 0.7]}
            rotation={[Math.PI / 2, -0.13, -Math.PI / 2]}
         />
         <mesh
            geometry={nodes.Menu_Images002.geometry}
            material={materials['Menu - Main.002']}
            position={[-1.16, 2.493, 0.7]}
            rotation={[Math.PI / 2, -0.13, -Math.PI / 2]}
         />
         <mesh
            geometry={nodes.Menu_Images003.geometry}
            material={materials['Menu - Contacts.002']}
            position={[-1.16, 2.493, 0.7]}
            rotation={[Math.PI / 2, -0.13, -Math.PI / 2]}
         />
         <mesh
            geometry={nodes.World.geometry}
            material={materials['PaletteMaterial001.003']}
            position={[0.166, 0.304, 0.259]}
            scale={26.661}
         />
         <mesh
            geometry={nodes['Text_-_Jerry'].geometry}
            material={nodes['Text_-_Jerry'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
         <mesh
            geometry={nodes['Text_-_About'].geometry}
            material={nodes['Text_-_About'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
         <mesh
            geometry={nodes['Text_-_Projects'].geometry}
            material={nodes['Text_-_Projects'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
         <mesh
            geometry={nodes['Text_-_Experience'].geometry}
            material={nodes['Text_-_Experience'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
         <mesh
            geometry={nodes['Text_-_Blog'].geometry}
            material={nodes['Text_-_Blog'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
         <mesh
            geometry={nodes['Text_-_Menu'].geometry}
            material={nodes['Text_-_Menu'].material}
            position={[2.088, 1.977, -1.217]}
            rotation={[Math.PI / 2, 0, 0]}
         />
      </group>
   );
}

useGLTF.preload('/real_portfolio.glb');
